### ISSUE TITLE
[Milestone] M1

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1248]
- [ ] Refactor app.js - https://github.com/ethereum/remix-ide/issues/701
 - [ ] Refactor tabs - https://github.com/ethereum/remix-ide/issues/1232
 - [ ] UX run tab - https://github.com/ethereum/remix-ide/issues/1153
 - [ ] UX input paramaters contract interaction - https://github.com/ethereum/remix-ide/issues/953
 - [ ] `Remix-tests` alpha release 
 - [ ] Public API in Remix-tests for a friendly use in CI and remix-ide
 - [ ] `Remix-tests` tab
 - [ ] Validate Plugin API messages format - https://github.com/ethereum/remix-ide/issues/1156
