### ISSUE TITLE
Add new (reserved) Solidity 0.5.0 keywords to syntax highlighting

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#1359]
PR https://github.com/ethereum/remix-ide/pull/1333

@raphaelhuefner

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.22 ETH (103.07 USD @ $468.49/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/remix-ide/1359/613).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $24,293.42 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by vs77bb** [comment]
@raphaelhuefner Would you like to claim this one on Gitcoin?

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 4 weeks, 1 day from now. Please review their questions below:


1. [Legitimate](https://gitcoin.co/profile/Legitimate) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?mutate_worker_action=approve&worker=Legitimate) | [reject worker](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?mutate_worker_action=reject&worker=Legitimate))_. 	
 * Q: I plan on installing thebrequired software to begin developing for this project. Is there a slack channel I may join?

**Comment by raphaelhuefner** [comment]
Sorry, forgot the most important step for the

## Action Plan:

- Re-integrate separate NPM package into remix-ide.

**Comment by yann300** [comment]
@raphaelhuefner what do you mean exactly by ` remix-ide's testing.` and `testing setup` ?

**Comment by yann300** [comment]
oh by `remix-ide's testing ` you mean using the compile, run and debugger tab from the right panel right?

**Comment by yann300** [comment]
or do you men end-to-end browser testing?

**Comment by raphaelhuefner** [comment]
@yann300 No, not the Solidity testing in the UI, I meant everything in these directories:

- https://github.com/ethereum/remix-ide/tree/master/test-browser-debugger/test
- https://github.com/ethereum/remix-ide/tree/master/test-browser
- https://github.com/ethereum/remix-ide/tree/master/test

I.e. Nightwatch and Saucelabs and friends.

**Comment by yann300** [comment]
ok thanks
yes that's a good thing to test ace highlighting separately.
Please sync up with @ryestew who worked on the remix ui theming feature, rob might have some insight.

**Comment by raphaelhuefner** [comment]
Will do that!

**Comment by vs77bb** [comment]
Raphael's plan was accepted. @legitimate Thanks for your interest! Please be on the lookout for other tickets [here](gitcoin.co/explorer).

**Comment by raphaelhuefner** [comment]
## Status Update

- No new syntax highlighting behavior yet.
- Headless testing is working now. (With [puppeteer](https://www.npmjs.com/package/puppeteer) instead of [run-headless](https://www.npmjs.com/package/run-headless).)
- Claimed this NPM package name: https://www.npmjs.com/package/ace-mode-solidity .
- Source at https://github.com/raphaelhuefner/ace-mode-solidity .
- Next step is creating all those Solidity code snippets.

**Comment by vs77bb** [comment]
Thanks for the update, @raphaelhuefner!

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=100)

**Comment by raphaelhuefner** [comment]
Hi all,

I'm still creating Solidity code snippets to test the syntax highlighting with. So far I have covered about 45% of `grammar.txt`.

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=100)

**Comment by raphaelhuefner** [comment]
Yep, still working on this. As per previous "Next Steps", it's currently a mix of these two things:
- Fixing all obvious tokenization errors in the current tokenizations, which were produced by the current `mode-solidity.js` "as-is".
- Refactoring `mode-solidity.js` to support more/new syntax.

**Comment by raphaelhuefner** [comment]
## Status Update
Consider the argument types of function `difficultSyntaxHighlight()`:
```solidity
pragma solidity ^0.4.24;

contract NestedParenthesesInFunctionArguments {
  mapping(uint256 => address) internal contrived;

  function difficultSyntaxHighlight(
    function(mapping(uint256 => address), bool) internal returns(bool) callbackParam,
    bool simpleParam
  ) internal returns(bool) {
    return callbackParam(contrived, simpleParam);
  }
}
```

An ACE syntax highlighter is supposed to mark `callbackParam` and `simpleParam` with token type `variable.parameter`. Not with `identifier` like outside the function argument list.

`mapping`s and `function` types use parentheses for their definitions. Those have to be nested inside the parentheses of function definitions. Because of this nesting, I have to start using the poorly documented `stack`/`push`/`pop` functionality available to ACE syntax highlighting instead of just dropping out of the `function_arguments` state on encountering the first closing parenthesis like the JS highlighter does.

So that is where I'm at right now.

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=100)

**Comment by raphaelhuefner** [comment]
Yes, still working on it. I solved the problem function arguments in https://github.com/ethereum/remix-ide/issues/1359#issuecomment-402183455

Next step is to create a PR against remix-ide to integrate what I did.

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=100)

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=100)

**Comment by raphaelhuefner** [comment]
I'm waiting for PR #1415 to get reviewed and then hopefully, merged.

**Comment by vs77bb** [comment]
Thanks for the update @raphaelhuefner!

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1359/613?snooze=100)

**Comment by raphaelhuefner** [comment]
@gitcoinbot Yes, still working on it. 

@ ryestew gave me some feedback on my PR in gitter, which I'm now incorporating.

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 0.22000  ETH (61.68 USD @ $280.38/ETH) has been granted to @raphaelhuefner for this issue from @vs77bb. ⚡️ 

Nice work @raphaelhuefner! Your tip has automatically been deposited in the ETH address we have on file.

 * $18575.31 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 0.22 ETH (61.68 USD @ $280.38/ETH)  attached to this issue has been approved & issued.__  

 * Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/remix-ide/1359/613)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $18,575.31 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by yann300** [comment]
@ryestew @raphaelhuefner are you good to close this one? or is there a remaining PR?

**Comment by raphaelhuefner** [comment]
@yann300 Yes, this one can be closed. 

There is some follow-up work which is related, but it's own functionality, so @ryestew allowed me to keep it in [a separate issue](https://github.com/ethereum/remix-ide/issues/1481).
