### ISSUE TITLE
Create custom ACE themes

### ISSUE THREAD

**Issue by raphaelhuefner** [ethereum/remix-ide#1481]
Follow-up to https://github.com/ethereum/remix-ide/issues/1359 and https://github.com/ethereum/remix-ide/pull/1415 , as discussed with @ryestew :

- one custom light ACE theme based on `node_modules/brace/theme/textmate.js`
- one custom dark ACE theme based on `node_modules/brace/theme/tomorrow_night_blue.js`
- inject colors from `src/app/ui/styles-guide/style-guide.js` or `src/app/ui/styles-guide/styleGuideDark.js` into ACE theme at runtime
- try to replace the colors taken from `textmate.js` and `tomorrow_night_blue.js` with closest matching colors already existing in `style-guide.js` and `styleGuideDark.js`, where feasible
- if there is no close match, add new colors into `style-guide.js` and `styleGuideDark.js`
- provide additional styling for Solidity-specific syntax highlighting classes

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 125.0 DAI (125.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $19,784.33 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


1. [raphaelhuefner](https://gitcoin.co/profile/raphaelhuefner) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?mutate_worker_action=approve&worker=raphaelhuefner) | [reject worker](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?mutate_worker_action=reject&worker=raphaelhuefner))_. 
    
    Hello there! Here is my

# Action plan
- copy `node_modules/brace/theme/textmate.js` and `node_modules/brace/theme/tomorrow_night_blue.js` into the `remix-ide` code base
- use the [`CIEDE2000` algorithm](https://www.npmjs.com/search?q=CIEDE2000) to calculate [color differences](https://en.wikipedia.org/wiki/Color_difference) between:
    - `src/app/ui/styles-guide/style-guide.js` ↔ `textmate.js`
    - `src/app/ui/styles-guide/styleGuideDark.js` ↔ `tomorrow_night_blue.js`
    - (Keep in mind that the Remix IDE style guides use `hsla()` and the ACE stock themes use `#hexRGB`, so I have to convert colors anyways to find matches. So I might as well do the whole `CIEDE2000` thing.)
- reference closest color matches from `style-guide.js` in `textmate.js`, and from `styleGuideDark.js` in `tomorrow_night_blue.js` by using string interpolation in JS template string literals like in `src/app/editor/editor.js`
- add any colors without close matches back into `style-guide.js` and `styleGuideDark.js`
- add extra styles for Solidity-specific syntax highlighting
- rename ACE themes as they now are not `textmate` and `tomorrow_night_blue` anymore

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032).

**Comment by raphaelhuefner** [comment]
Copied from gitter:

ryestew:

It seems that since the merge the `type` is no longer highlighted.  Do you know if other things are not highlighted as they were?  Is this something that get fixed in the next PR?  Or would it be possible to make an update the returns this highlighting - to what it was before?   Let me know what you think.

raphaelhuefner:

If I understand correctly what is meant by "type" here, then I have to say:

The tokenization for most types like `bool`, `string`, `byte`, `bytes`, `address` and all the `int*` types, changed from "variable.language" to "storage.type".

According to https://github.com/ajaxorg/ace/wiki/Creating-or-Extending-an-Edit-Mode#commonTokens:

> "variable.language" - is for reserved language variables like `this`, `super`, `self`, etc.
> "storage.type" - the type of something, `class`, `function`, `int`, `var`, etc.

With the next PR, I can look into re-using as many of the "old colors" for the new tokenizations as possible. If that's not possible one to one, then some tokenizations can get "refined" with additional classes. `bytes` and `string` have "storage.type.array.dynamic" already, for example.

**Comment by ryestew** [comment]
Hi Raphael - I have a couple of questions - its sort of prosiac but - the color of a word like bool changed from a a pale green to the blue that it currently is in remix-alpha.ethereum.org ( the old version is remix.ethereum.org)  So we can tune the colors of the span in the next PR - but in the mean time, the code is a bit harder to read because it lacks the differentiation that it had.  

Do you have an idea when you’ll get to this?  Is there a quick fix to make the storage.type words the same green that they had been when they were variable.language?

**Comment by raphaelhuefner** [comment]
Hi @ryestew,

Looks like I should tackle the "re-using of old colors with new tokenizations" first, before matching colors between style guide and ACE theme.

I think I can get to that this week, I hope it can be merged before the coming weekend.

**Comment by ryestew** [comment]
Hi @raphaelhuefner - great - thanks so much!

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=100)

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=100)

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=100)

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=100)

**Comment by raphaelhuefner** [comment]
@gitcoinbot Yes, I'm still working on this, sorting out *all the colors* ;-)

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=100)

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@raphaelhuefner due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] warning (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=100)

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=100)

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=100)

**Comment by raphaelhuefner** [comment]
@gitcoinbot Still working on this, albeit slowly, because these days I have to relocate for a new job in a blockchain company.

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=100)

**Comment by raphaelhuefner** [comment]
Hey @ryestew ,

I finally, finally figured out which colors to change so that the new tokenizations don't turn from the pale green to deep blue. I.e. what you were talking about [about a month ago](https://github.com/ethereum/remix-ide/issues/1481#issuecomment-416374797).

While going down a rabbit-hole of "color reports" (pls don't ask ;-) ), I discovered a few more tokenizations which "turned blue" in the textmate theme. Here is a list: https://rawgit.com/raphaelhuefner/d8e37a4b3252cbbf738917a607056675/raw/ed0a771d3321938e7d35b0bee94ac60eb1a224bd/color-blue-report.html

Could you please advise me which colors instead of blue these tokenizations should be?

I included one which "turned red" because I feel that the red might be misunderstood as an error message and should also be changed to something else. Many other constants are in a bright purple, `rgb(88, 92, 246)`, could that be an option?

Thank you for your patience!
Raphael

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=100)

**Comment by raphaelhuefner** [comment]
Yes, still working on it. Now I'm prepping the first of two PRs which changes the colors so that they appear as before the tokenizer upgrade.

**Comment by gitcoinbot** [comment]
@raphaelhuefner Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/remix-ide/1481/1032?snooze=100)

**Comment by raphaelhuefner** [comment]
Waiting for feedback from @ryestew .

**Comment by vs77bb** [comment]
Hi @ryestew is this one still in review with you? cc @raphaelhuefner

**Comment by ryestew** [comment]
yes it is - I will have more about it tomorrow.

Rob

**Comment by ryestew** [comment]
@raphaelhuefner - I'm sorry I missed the notification about your update 19 days ago.  I'm contacting the solidity team for their view of colors and differentiation of key words.  I'll have an update as soon as I hear back from them.

**Comment by raphaelhuefner** [comment]
@ryestew Here is a pull request to show how to bring those old colors back. Adding new colors will be just as easy. ;-)

**Comment by ryan-shea** [comment]
Hey @ryestew, Ryan from Gitcoin here. Have you heard back from the solidity team? Want to make sure that this bounty is moving along 😄 🗺 

If you have any questions please let me know! I will snooze Gitcoin bot for a few extra days.

**Comment by ryan-shea** [comment]
Hey @vs77bb, looks like this one is ready to be reviewed!

**Comment by ryestew** [comment]
I'll have it reviewed before Tuesday.

**Comment by ryan-shea** [comment]
Hey @ryestew, any updates here? 😄

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__The funding of 125.0 DAI  (125.0 USD @ $1.0/DAI) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $135,623.32 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
