### ISSUE TITLE
Solidity Static Plugin Analysis Enhancements

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-ide#2812]
- [ ] add a checkbox to checkAll to each categorie #2772 
- [ ] highlight source location #2808 
- [ ] show expandable modules and not accordion #2810
