### ISSUE TITLE
Solidity Unit Testing Plugin Enhancements

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/remix-ide#2813]
- [ ] Improve contract name of generated sample test file #2758 
- [ ] Discuss and decide where should generated sample test file reside in file explorer #2765 
- [ ] Add custom transaction context tests for 'Solidity Unit Testing' #2745
