### ISSUE TITLE
TODO 0.6

### ISSUE THREAD

**Issue by yann300** [ethereum/remix-ide#791]
- [x] remixd bug fix: https://github.com/ethereum/remixd/issues/6 @serapath 
	list() should not recursvely load everything recursively. cause that crashes remixd
---
- [ ] Small UI fixes - https://github.com/ethereum/browser-solidity/issues/824
---
- [x] Debugger GUI
---
- [ ] IDE features @ninabreznik 
	https://github.com/ethereum/browser-solidity/issues/640 - done
	https://github.com/ethereum/browser-solidity/issues/619 - done
	https://github.com/ethereum/browser-solidity/issues/618 - done
	https://github.com/ethereum/browser-solidity/issues/721 - done 
        https://github.com/ethereum/browser-solidity/pull/930/files - done

    - https://github.com/ethereum/browser-solidity/issues/780
    - Add search icon to start searching (next to ctrl-f) 
    - if selected AST item is a function, display the gas estimation  - **in review**
    - cmd-d (update declaration name, all selected ones)
---
 - [ ] decode mapping (geth) https://github.com/ethereum/remix/issues/564
	web3.debug.preimage returns an error
---
 - [ ] ~ens (publish ABI): https://github.com/ethereum/browser-solidity/issues/550~
	~A lot has already be done (see ens branch) - that needs testing on ropsten/rinkeby~
---
 - [ ] ~web3 actions: (if possible make it available when using web3 provider, if not should try with the mist integration)~
	~start/stop mining from geth~
 	~use web3.personal.sendTransaction~
---
- [ ] ~Use ABI file directly: https://github.com/ethereum/browser-solidity/pull/700~
 	~if the file has *.abi, don't try to compile but allow to use the "At address" feature. so non compiled contracts can be referenced too. ~
	~we should also only try to compile *.sol files. ~
---
- [ ] start page
---
- [ ] make tutorials
---
- [ ] publish to gist: https://github.com/ethereum/browser-solidity/issues/739
	Works ok but user experience needs to be improved
---
- [x] style-guide: https://github.com/ethereum/browser-solidity/issues/706
	a lot of refactor to do + Remix light and dark theme and Metropolis
---
- [x] GUI fixes https://github.com/ethereum/browser-solidity/issues/795
---
- [x] Check how Metropolis forks (opcode, gasprice, ...) interfers and fix
---
- [x] Record transactions: https://github.com/ethereum/browser-solidity/issues/490
	in `run-tab`, action to save transactions to a json file so it can be replayed. ask the user where the record should be saved (either in browser/ or localhost if available).
---
- [x] Record transaction GUI
---
 - [x] Mist integration integrate a way to command the integrated geth node (Make a Demo) 
---
 - [x] jsonio integration: https://github.com/ethereum/browser-solidity/issues/531
---
- [x] publish to swarm: https://github.com/ethereum/browser-solidity/issues/756
	Works ok but user experience needs to be improved
---
- [x] integrate the metropolis theme
---

**Comment by ninabreznik** [comment]
`Record transactions` could be called `Save transaction template`

**Comment by ninabreznik** [comment]
I think we could add this issue somewhere

- brainstorm Improvements of file-panel and editor-tabs:
  * renaming (also enabling to change path), 
  * adding files to folders, 
  * making all tabs always visible (like in atom, they just become narrower when more tabs) - i would personally leave tabs
  * maybe add (close tabs on the right, close all tabs, close tabs to the left etc.) - later
  * etc.

**Comment by ninabreznik** [comment]
And we should check what is going on in Firefox. OR add somewhere on the page that we recommend people to use Remix on Chrome v. something or higher.

**Comment by yann300** [comment]
closing as most of these issues are addressed
